#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np


CODE_ROOT = Path(__file__).resolve().parents[2]
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

from evttc.native_adapter import NativeSampleAdapter


DEFAULT_METRICS_CSV = (
    CODE_ROOT
    / "Experiments"
    / "SparsityAwareLTS"
    / "BBoxLoomingV13_20260427_212537"
    / "IntervalMetrics.csv"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Classify BBoxLooming residuals into thesis-ready failure types.",
    )
    parser.add_argument(
        "--formal-root",
        type=Path,
        default=CODE_ROOT / "DatasetFormal",
        help="Root directory of formal sequence artifacts.",
    )
    parser.add_argument(
        "--metrics-csv",
        type=Path,
        default=DEFAULT_METRICS_CSV,
        help="IntervalMetrics.csv generated by a BBoxLooming run.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=CODE_ROOT / "Experiments" / "SparsityAwareLTSDiagnostics",
        help="Root directory for diagnostics outputs.",
    )
    parser.add_argument("--high-error-threshold", type=float, default=50.0)
    parser.add_argument("--severe-error-threshold", type=float, default=100.0)
    parser.add_argument("--history-back", type=int, default=12)
    parser.add_argument("--area-collapse-ratio", type=float, default=0.20)
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def as_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def as_int(value: object) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except ValueError:
        return None


def fmt(value: float | None, digits: int = 6) -> str:
    if value is None or not math.isfinite(value):
        return ""
    return f"{value:.{digits}f}"


def parse_fit_points(debug_ref: str) -> int | None:
    for part in str(debug_ref).split(";"):
        key, _, value = part.partition("=")
        if key.strip() == "fit_points":
            return as_int(value)
    return None


def safe_stats(values: list[float]) -> dict[str, float | int | None]:
    if not values:
        return {"count": 0, "mean": None, "median": None, "p90": None, "max": None}
    arr = np.asarray(values, dtype=np.float64)
    return {
        "count": int(arr.size),
        "mean": float(arr.mean()),
        "median": float(np.percentile(arr, 50)),
        "p90": float(np.percentile(arr, 90)),
        "max": float(arr.max()),
    }


def bbox_area(record: object) -> float:
    return max(0.0, float((record.x2 - record.x1) * (record.y2 - record.y1)))


def bbox_ratio_features(adapter: NativeSampleAdapter, sample_id: str, history_back: int) -> dict[str, float | int | str]:
    sample = adapter.reader.get_interval_sample(sample_id=sample_id)
    lo = sample.start_label_id - history_back
    hi = sample.start_label_id + 2
    records = sorted(
        [record for record in adapter.bbox_records if lo <= record.label_id <= hi],
        key=lambda item: item.label_id,
    )
    current_records = [record for record in records if record.label_id == sample.start_label_id]
    current = current_records[-1] if current_records else None
    previous = [record for record in records if record.label_id < sample.start_label_id]
    next_records = [record for record in records if record.label_id == sample.start_label_id + 1]
    next_record = next_records[-1] if next_records else None

    out: dict[str, float | int | str] = {
        "interval_fraction": sample.interval_idx / max(len(adapter.reader.interval_samples) - 1, 1),
        "event_count": sample.event_count,
        "history_record_count": len(previous) + (1 if current is not None else 0),
        "history_collapse_count": 0,
        "history_collapse_label_ids": "",
    }
    if current is None:
        return out

    current_area = bbox_area(current)
    previous_areas = [bbox_area(record) for record in previous]
    out["current_area"] = current_area
    if previous_areas:
        out["area_ratio_prev"] = current_area / max(previous_areas[-1], 1e-6)
        out["area_ratio_med5"] = current_area / max(float(np.median(previous_areas[-5:])), 1e-6)
    if next_record is not None:
        out["next_area_ratio_current"] = bbox_area(next_record) / max(current_area, 1e-6)

    collapse_label_ids: list[str] = []
    all_records = [record for record in records if record.label_id <= sample.start_label_id]
    areas = [bbox_area(record) for record in all_records]
    for idx, record in enumerate(all_records):
        before = areas[max(0, idx - 2):idx]
        after = areas[idx + 1:idx + 3]
        if not before or not after:
            continue
        neighbor_area = float(np.median(np.asarray([*before, *after], dtype=np.float64)))
        if neighbor_area > 0.0 and areas[idx] / neighbor_area < 0.20:
            collapse_label_ids.append(str(record.label_id))
    out["history_collapse_count"] = len(collapse_label_ids)
    out["history_collapse_label_ids"] = "|".join(collapse_label_ids)
    return out


def gt_bucket(gt_ttc_s: float | None) -> str:
    if gt_ttc_s is None:
        return "GT_INVALID"
    if gt_ttc_s <= 1.0:
        return "<=1s"
    if gt_ttc_s <= 2.0:
        return "1-2s"
    if gt_ttc_s <= 3.5:
        return "2-3.5s"
    if gt_ttc_s <= 6.0:
        return "3.5-6s"
    return ">6s"


def status_family(status: str) -> str:
    if status == "GT_INVALID":
        return "GT_INVALID"
    if not status.startswith("OK"):
        return "NO_PRED"
    if "LOWFIT" in status:
        return "LOWFIT"
    if "LOWCAND" in status:
        return "LOWCAND"
    if "DISP" in status:
        return "DISP"
    if "PHASEEARLY" in status:
        return "PHASEEARLY"
    if "PHASEGROWTH" in status:
        return "PHASEGROWTH"
    if "PHASESTABLE" in status:
        return "PHASESTABLE"
    if "PHASELATE" in status:
        return "PHASELATE"
    if "CURGUARD" in status:
        return "CURGUARD"
    if "HISTGUARD" in status:
        return "HISTGUARD"
    if status == "OK_BBOX_MULTI_Q25":
        return "HIGH_CONF_Q25"
    return "OK_OTHER"


def classify_row(row: dict[str, object], high_error_threshold: float) -> tuple[str, str]:
    status = str(row["status"])
    e_ttc_pct = as_float(row.get("e_ttc_pct"))
    pred_over_gt = as_float(row.get("pred_over_gt"))
    history_collapse_count = int(row.get("history_collapse_count") or 0)
    area_ratio_med5 = as_float(row.get("area_ratio_med5"))
    status_group = status_family(status)

    flags: list[str] = []
    if area_ratio_med5 is not None and area_ratio_med5 < 0.20:
        flags.append("current_bbox_collapse_signal")
    if history_collapse_count > 0:
        flags.append("history_bbox_collapse_signal")
    if pred_over_gt is not None:
        flags.append("overestimate" if pred_over_gt >= 1.0 else "underestimate")

    if e_ttc_pct is None:
        primary = "NO_VALID_PREDICTION"
    elif e_ttc_pct <= high_error_threshold:
        if "CURGUARD" in status or "HISTGUARD" in status:
            primary = "REPAIRED_LOW_ERROR_GUARD_SAMPLE"
        else:
            primary = "LOW_ERROR_ACCEPTED"
    else:
        direction = "OVER" if (pred_over_gt or 0.0) >= 1.0 else "UNDER"
        if "LOWFIT" in status:
            primary = f"LOWFIT_{direction}"
        elif "LOWCAND" in status:
            primary = f"LOWCAND_{direction}"
        elif "DISP" in status:
            primary = f"HIGH_DISPERSION_{direction}"
        elif "PHASEEARLY" in status:
            primary = f"PHASEEARLY_RESIDUAL_{direction}"
        elif "PHASEGROWTH" in status:
            primary = f"PHASEGROWTH_RESIDUAL_{direction}"
        elif "PHASESTABLE" in status:
            primary = f"PHASESTABLE_RESIDUAL_{direction}"
        elif "PHASELATE" in status:
            primary = f"PHASELATE_RESIDUAL_{direction}"
        elif "CURGUARD" in status:
            primary = f"CURRENT_BBOX_GUARD_RESIDUAL_{direction}"
        elif "HISTGUARD" in status:
            primary = f"HISTORY_BBOX_GUARD_RESIDUAL_{direction}"
        elif area_ratio_med5 is not None and area_ratio_med5 < 0.20:
            primary = f"UNGUARDED_CURRENT_BBOX_COLLAPSE_{direction}"
        elif history_collapse_count > 0:
            primary = f"UNGUARDED_HISTORY_BBOX_COLLAPSE_{direction}"
        elif status_group == "HIGH_CONF_Q25":
            primary = f"APPARENT_HIGH_CONF_GEOMETRY_{direction}"
        else:
            primary = f"OTHER_{status_group}_{direction}"
    return primary, "|".join(flags)


def make_summary_rows(rows: list[dict[str, object]], group_key: str, severe_threshold: float) -> list[dict[str, object]]:
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[str(row[group_key])].append(row)

    output: list[dict[str, object]] = []
    for group, items in grouped.items():
        valid_errors = [float(item["e_ttc_pct"]) for item in items if item["e_ttc_pct"] != ""]
        high_items = [item for item in items if item["is_high_error"] == "1"]
        severe_count = sum(
            1
            for item in items
            if item["e_ttc_pct"] != "" and float(item["e_ttc_pct"]) > severe_threshold
        )
        stats = safe_stats(valid_errors)
        examples = sorted(
            [item for item in items if item["e_ttc_pct"] != ""],
            key=lambda item: float(item["e_ttc_pct"]),
            reverse=True,
        )[:5]
        output.append(
            {
                group_key: group,
                "row_count": len(items),
                "valid_prediction_count": stats["count"],
                "high_error_count": len(high_items),
                "severe_error_count": severe_count,
                "mean_e_ttc_pct": fmt(stats["mean"], digits=3),
                "median_e_ttc_pct": fmt(stats["median"], digits=3),
                "p90_e_ttc_pct": fmt(stats["p90"], digits=3),
                "max_e_ttc_pct": fmt(stats["max"], digits=3),
                "example_samples": ";".join(str(item["sample_id"]) for item in examples),
            }
        )
    return sorted(
        output,
        key=lambda item: (
            -int(item["high_error_count"]),
            -float(item["mean_e_ttc_pct"] or 0.0),
            str(item[group_key]),
        ),
    )


def rejection_scenarios(rows: list[dict[str, object]], high_error_threshold: float) -> list[dict[str, object]]:
    scenarios = {
        "keep_all_valid": lambda row: row["e_ttc_pct"] != "",
        "reject_lowfit": lambda row: row["e_ttc_pct"] != "" and row["status_family"] != "LOWFIT",
        "reject_lowfit_lowcand": lambda row: row["e_ttc_pct"] != "" and row["status_family"] not in {"LOWFIT", "LOWCAND"},
        "reject_lowfit_lowcand_disp": lambda row: row["e_ttc_pct"] != "" and row["status_family"] not in {"LOWFIT", "LOWCAND", "DISP"},
        "reject_all_high_error": lambda row: row["e_ttc_pct"] != "" and float(row["e_ttc_pct"]) <= high_error_threshold,
    }
    output: list[dict[str, object]] = []
    valid_total = sum(1 for row in rows if row["e_ttc_pct"] != "")
    for name, keep_fn in scenarios.items():
        kept = [row for row in rows if keep_fn(row)]
        errors = [float(row["e_ttc_pct"]) for row in kept]
        stats = safe_stats(errors)
        output.append(
            {
                "scenario": name,
                "kept_valid_count": len(kept),
                "rejected_valid_count": valid_total - len(kept),
                "kept_valid_ratio": fmt(len(kept) / max(valid_total, 1), digits=3),
                "mean_e_ttc_pct": fmt(stats["mean"], digits=3),
                "median_e_ttc_pct": fmt(stats["median"], digits=3),
                "p90_e_ttc_pct": fmt(stats["p90"], digits=3),
                "over50_count": sum(1 for value in errors if value > high_error_threshold),
            }
        )
    return output


def main() -> None:
    args = parse_args()
    metric_rows = read_csv(args.metrics_csv.resolve())
    run_ts = datetime.now().strftime("BBoxFailureTypeReport_%Y%m%d_%H%M%S")
    run_dir = args.output_root.resolve() / run_ts
    run_dir.mkdir(parents=True, exist_ok=True)

    adapters: dict[str, NativeSampleAdapter] = {}
    typed_rows: list[dict[str, object]] = []
    try:
        for metric_row in metric_rows:
            sequence_id = metric_row["sequence_id"]
            if sequence_id not in adapters:
                adapters[sequence_id] = NativeSampleAdapter(
                    sequence_id,
                    formal_root=args.formal_root.resolve(),
                )
            adapter = adapters[sequence_id]

            gt_ttc_s = as_float(metric_row.get("gt_ttc_s"))
            pred_ttc_s = as_float(metric_row.get("ttc_est_s"))
            e_ttc_pct = as_float(metric_row.get("e_ttc_pct"))
            pred_over_gt = None
            if gt_ttc_s is not None and pred_ttc_s is not None and gt_ttc_s > 0.0:
                pred_over_gt = pred_ttc_s / gt_ttc_s
            features = bbox_ratio_features(
                adapter,
                metric_row["sample_id"],
                args.history_back,
            )
            row: dict[str, object] = {
                "sample_id": metric_row["sample_id"],
                "sequence_id": sequence_id,
                "interval_idx": metric_row["interval_idx"],
                "gt_ttc_s": fmt(gt_ttc_s),
                "pred_ttc_s": fmt(pred_ttc_s),
                "e_ttc_pct": fmt(e_ttc_pct),
                "pred_over_gt": fmt(pred_over_gt),
                "status": metric_row["status"],
                "status_family": status_family(metric_row["status"]),
                "fit_points": parse_fit_points(metric_row.get("debug_ref", "")) or "",
                "gt_bucket": gt_bucket(gt_ttc_s),
                "is_high_error": "1"
                if e_ttc_pct is not None and e_ttc_pct > args.high_error_threshold
                else "0",
                "is_severe_error": "1"
                if e_ttc_pct is not None and e_ttc_pct > args.severe_error_threshold
                else "0",
                "debug_ref": metric_row.get("debug_ref", ""),
                **{key: fmt(value) if isinstance(value, float) else value for key, value in features.items()},
            }
            primary, flags = classify_row(row, args.high_error_threshold)
            row["primary_failure_type"] = primary
            row["flags"] = flags
            typed_rows.append(row)
    finally:
        for adapter in adapters.values():
            adapter.close()

    fieldnames = [
        "sample_id",
        "sequence_id",
        "interval_idx",
        "gt_ttc_s",
        "pred_ttc_s",
        "e_ttc_pct",
        "pred_over_gt",
        "status",
        "status_family",
        "primary_failure_type",
        "flags",
        "gt_bucket",
        "is_high_error",
        "is_severe_error",
        "fit_points",
        "interval_fraction",
        "event_count",
        "history_record_count",
        "current_area",
        "area_ratio_prev",
        "area_ratio_med5",
        "next_area_ratio_current",
        "history_collapse_count",
        "history_collapse_label_ids",
        "debug_ref",
    ]
    write_csv(run_dir / "IntervalFailureTypes.csv", typed_rows, fieldnames)

    high_rows = [row for row in typed_rows if row["is_high_error"] == "1"]
    write_csv(run_dir / "HighErrorIntervals.csv", high_rows, fieldnames)

    type_summary = make_summary_rows(typed_rows, "primary_failure_type", args.severe_error_threshold)
    status_summary = make_summary_rows(typed_rows, "status_family", args.severe_error_threshold)
    sequence_summary = make_summary_rows(typed_rows, "sequence_id", args.severe_error_threshold)
    write_csv(
        run_dir / "FailureTypeSummary.csv",
        type_summary,
        [
            "primary_failure_type",
            "row_count",
            "valid_prediction_count",
            "high_error_count",
            "severe_error_count",
            "mean_e_ttc_pct",
            "median_e_ttc_pct",
            "p90_e_ttc_pct",
            "max_e_ttc_pct",
            "example_samples",
        ],
    )
    write_csv(
        run_dir / "StatusFamilySummary.csv",
        status_summary,
        [
            "status_family",
            "row_count",
            "valid_prediction_count",
            "high_error_count",
            "severe_error_count",
            "mean_e_ttc_pct",
            "median_e_ttc_pct",
            "p90_e_ttc_pct",
            "max_e_ttc_pct",
            "example_samples",
        ],
    )
    write_csv(
        run_dir / "SequenceFailureTypeSummary.csv",
        sequence_summary,
        [
            "sequence_id",
            "row_count",
            "valid_prediction_count",
            "high_error_count",
            "severe_error_count",
            "mean_e_ttc_pct",
            "median_e_ttc_pct",
            "p90_e_ttc_pct",
            "max_e_ttc_pct",
            "example_samples",
        ],
    )
    scenario_rows = rejection_scenarios(typed_rows, args.high_error_threshold)
    write_csv(
        run_dir / "RejectionScenarios.csv",
        scenario_rows,
        [
            "scenario",
            "kept_valid_count",
            "rejected_valid_count",
            "kept_valid_ratio",
            "mean_e_ttc_pct",
            "median_e_ttc_pct",
            "p90_e_ttc_pct",
            "over50_count",
        ],
    )

    valid_errors = [float(row["e_ttc_pct"]) for row in typed_rows if row["e_ttc_pct"] != ""]
    overall = safe_stats(valid_errors)
    high_count = sum(1 for row in typed_rows if row["is_high_error"] == "1")
    severe_count = sum(1 for row in typed_rows if row["is_severe_error"] == "1")
    payload = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "metrics_csv": str(args.metrics_csv.resolve()),
        "formal_root": str(args.formal_root.resolve()),
        "high_error_threshold": args.high_error_threshold,
        "severe_error_threshold": args.severe_error_threshold,
        "valid_prediction_count": overall["count"],
        "mean_e_ttc_pct": overall["mean"],
        "median_e_ttc_pct": overall["median"],
        "p90_e_ttc_pct": overall["p90"],
        "max_e_ttc_pct": overall["max"],
        "high_error_count": high_count,
        "severe_error_count": severe_count,
    }
    (run_dir / "Config.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    lines = [
        "# BBox Failure Type Report",
        "",
        f"- run_dir: `{run_dir}`",
        f"- metrics_csv: `{args.metrics_csv.resolve()}`",
        f"- valid_prediction_count: `{overall['count']}`",
        f"- mean_e_ttc_pct: `{fmt(overall['mean'], digits=3)}`",
        f"- median_e_ttc_pct: `{fmt(overall['median'], digits=3)}`",
        f"- p90_e_ttc_pct: `{fmt(overall['p90'], digits=3)}`",
        f"- high_error_count(>{args.high_error_threshold:g}%): `{high_count}`",
        f"- severe_error_count(>{args.severe_error_threshold:g}%): `{severe_count}`",
        "",
        "## Failure Types",
        "",
        "| type | rows | valid | high | severe | mean | p90 | examples |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in type_summary[:16]:
        lines.append(
            f"| `{row['primary_failure_type']}` | {row['row_count']} | {row['valid_prediction_count']} | "
            f"{row['high_error_count']} | {row['severe_error_count']} | {row['mean_e_ttc_pct']} | "
            f"{row['p90_e_ttc_pct']} | `{row['example_samples']}` |"
        )
    lines.extend(
        [
            "",
            "## Rejection Scenarios",
            "",
            "| scenario | kept | rejected | kept_ratio | mean | p90 | over50 |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for row in scenario_rows:
        lines.append(
            f"| `{row['scenario']}` | {row['kept_valid_count']} | {row['rejected_valid_count']} | "
            f"{row['kept_valid_ratio']} | {row['mean_e_ttc_pct']} | {row['p90_e_ttc_pct']} | "
            f"{row['over50_count']} |"
        )
    lines.extend(
        [
            "",
            "## Files",
            "",
            "- `IntervalFailureTypes.csv`",
            "- `HighErrorIntervals.csv`",
            "- `FailureTypeSummary.csv`",
            "- `StatusFamilySummary.csv`",
            "- `SequenceFailureTypeSummary.csv`",
            "- `RejectionScenarios.csv`",
            "",
        ]
    )
    (run_dir / "Summary.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"[Done] run_dir: {run_dir}")
    print(f"[Done] summary: {run_dir / 'Summary.md'}")


if __name__ == "__main__":
    main()
