#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable

import numpy as np


CODE_ROOT = Path(__file__).resolve().parents[2]
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

from evttc import NativeSampleAdapter
from evttc.formal_loader import BoundingBoxRecord
from evttc.sparsity_aware_lts import (
    BBoxLoomingConfigV1,
    _weighted_fit_residual,
    _weighted_linear_fit,
)


DEFAULT_METRICS_CSV = (
    CODE_ROOT
    / "Experiments"
    / "SparsityAwareLTS"
    / "BBoxLoomingV13_20260427_212537"
    / "IntervalMetrics.csv"
)
DEFAULT_FAILURE_TYPES_CSV = (
    CODE_ROOT
    / "Experiments"
    / "SparsityAwareLTSDiagnostics"
    / "BBoxFailureTypeReport_20260427_212614"
    / "IntervalFailureTypes.csv"
)
QUANTILES = (0.05, 0.10, 0.15, 0.25, 0.35, 0.50, 0.65, 0.75, 0.90)


@dataclass(frozen=True)
class CandidateRow:
    sample_id: str
    sequence_id: str
    interval_idx: int
    cue_name: str
    history_back: int
    fit_points: int
    ttc_s: float
    slope_px_per_s: float
    ref_px: float
    normalized_residual: float
    relative_slope: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Diagnose V11 high-confidence BBoxLooming geometry errors by recomputing "
            "multi-window candidate TTC quantiles."
        ),
    )
    parser.add_argument(
        "--formal-root",
        type=Path,
        default=CODE_ROOT / "DatasetFormal",
        help="Root directory of formal sequence artifacts.",
    )
    parser.add_argument(
        "--metrics-csv",
        type=Path,
        default=DEFAULT_METRICS_CSV,
        help="IntervalMetrics.csv generated by a BBoxLooming run.",
    )
    parser.add_argument(
        "--failure-types-csv",
        type=Path,
        default=DEFAULT_FAILURE_TYPES_CSV,
        help="Optional IntervalFailureTypes.csv generated by run_bbox_failure_type_report.py.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=CODE_ROOT / "Experiments" / "SparsityAwareLTSDiagnostics",
        help="Root directory for diagnostics outputs.",
    )
    parser.add_argument("--history-back", type=int, default=12)
    parser.add_argument("--history-min-back", type=int, default=2)
    parser.add_argument("--max-ttc", type=float, default=16.0)
    parser.add_argument("--candidate-quantile", type=float, default=0.25)
    parser.add_argument("--high-error-threshold", type=float, default=50.0)
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def as_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def as_int(value: object) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except ValueError:
        return None


def fmt(value: float | None, digits: int = 6) -> str:
    if value is None or not math.isfinite(value):
        return ""
    return f"{value:.{digits}f}"


def q_key(q: float) -> str:
    return f"q{int(round(q * 100)):02d}"


def safe_stats(values: list[float]) -> dict[str, float | int | None]:
    if not values:
        return {"count": 0, "mean": None, "median": None, "p90": None, "max": None}
    arr = np.asarray(values, dtype=np.float64)
    return {
        "count": int(arr.size),
        "mean": float(arr.mean()),
        "median": float(np.percentile(arr, 50)),
        "p90": float(np.percentile(arr, 90)),
        "max": float(arr.max()),
    }


def summarize_errors(rows: list[dict[str, object]], error_key: str, high_error_threshold: float) -> dict[str, object]:
    errors = [float(row[error_key]) for row in rows if row.get(error_key) not in (None, "")]
    stats = safe_stats(errors)
    return {
        "count": stats["count"],
        "mean_e_ttc_pct": fmt(stats["mean"], digits=3),
        "median_e_ttc_pct": fmt(stats["median"], digits=3),
        "p90_e_ttc_pct": fmt(stats["p90"], digits=3),
        "max_e_ttc_pct": fmt(stats["max"], digits=3),
        "over50_count": sum(1 for value in errors if value > high_error_threshold),
    }


def bbox_area(record: BoundingBoxRecord) -> float:
    return max(0.0, float((record.x2 - record.x1) * (record.y2 - record.y1)))


def bbox_ratio_features(
    records: tuple[BoundingBoxRecord, ...],
    *,
    start_label_id: int,
    interval_idx: int,
    interval_count: int,
    history_back: int,
) -> dict[str, float | int | str]:
    lo = start_label_id - history_back
    hi = start_label_id + 2
    local_records = sorted(
        [record for record in records if lo <= record.label_id <= hi],
        key=lambda item: item.label_id,
    )
    current_records = [record for record in local_records if record.label_id == start_label_id]
    current = current_records[-1] if current_records else None
    previous = [record for record in local_records if record.label_id < start_label_id]
    next_records = [record for record in local_records if record.label_id == start_label_id + 1]
    next_record = next_records[-1] if next_records else None

    out: dict[str, float | int | str] = {
        "interval_fraction": interval_idx / max(interval_count - 1, 1),
        "history_record_count": len(previous) + (1 if current is not None else 0),
        "history_collapse_count": 0,
        "history_collapse_label_ids": "",
    }
    if current is None:
        return out

    current_area = bbox_area(current)
    previous_areas = [bbox_area(record) for record in previous]
    out["current_area"] = current_area
    if previous_areas:
        out["area_ratio_prev"] = current_area / max(previous_areas[-1], 1e-6)
        out["area_ratio_med5"] = current_area / max(float(np.median(previous_areas[-5:])), 1e-6)
    if next_record is not None:
        out["next_area_ratio_current"] = bbox_area(next_record) / max(current_area, 1e-6)

    collapse_label_ids: list[str] = []
    all_records = [record for record in local_records if record.label_id <= start_label_id]
    areas = [bbox_area(record) for record in all_records]
    for idx, record in enumerate(all_records):
        before = areas[max(0, idx - 2):idx]
        after = areas[idx + 1:idx + 3]
        if not before or not after:
            continue
        neighbor_area = float(np.median(np.asarray([*before, *after], dtype=np.float64)))
        if neighbor_area > 0.0 and areas[idx] / neighbor_area < 0.20:
            collapse_label_ids.append(str(record.label_id))
    out["history_collapse_count"] = len(collapse_label_ids)
    out["history_collapse_label_ids"] = "|".join(collapse_label_ids)
    return out


def bottom_reference_y(adapter: NativeSampleAdapter, config: BBoxLoomingConfigV1) -> float:
    calibration = adapter.reader.calibration
    if config.bottom_reference == "principal_point":
        return float(calibration.intrinsics.get("cy", calibration.resolution["height"] * 0.5))
    if config.bottom_reference == "image_fraction":
        return float(calibration.resolution["height"]) * float(config.bottom_reference_fraction)
    return float(calibration.resolution["height"]) * 0.5


def dims_for_records(
    records: list[BoundingBoxRecord],
    *,
    bottom_ref_y: float,
    include_bottom_cue: bool,
) -> dict[str, np.ndarray]:
    widths = np.asarray([record.x2 - record.x1 for record in records], dtype=np.float64)
    heights = np.asarray([record.y2 - record.y1 for record in records], dtype=np.float64)
    bottom_y = np.asarray([record.y2 for record in records], dtype=np.float64)
    dimensions = {
        "width": widths,
        "height": heights,
        "diag": np.sqrt(np.square(widths) + np.square(heights)),
        "sqrt_area": np.sqrt(np.maximum(widths * heights, 1e-6)),
    }
    if include_bottom_cue:
        dimensions["bottom_offset"] = bottom_y - float(bottom_ref_y)
    return dimensions


def filter_history_bbox_collapses(
    records: list[BoundingBoxRecord],
    config: BBoxLoomingConfigV1,
) -> tuple[list[BoundingBoxRecord], int]:
    if len(records) < 3:
        return records, 0
    keep_records: list[BoundingBoxRecord] = []
    filtered_count = 0
    neighbor_back = max(1, int(config.history_bbox_collapse_neighbor_back))
    neighbor_forward = max(1, int(config.history_bbox_collapse_neighbor_forward))
    area_ratio_min = float(config.history_bbox_collapse_area_ratio_min)
    areas = [bbox_area(record) for record in records]
    for idx, record in enumerate(records):
        before = areas[max(0, idx - neighbor_back):idx]
        after = areas[idx + 1:idx + 1 + neighbor_forward]
        if before and after:
            neighbor_area = float(np.median(np.asarray([*before, *after], dtype=np.float64)))
            if neighbor_area > 0.0 and areas[idx] / neighbor_area < area_ratio_min:
                filtered_count += 1
                continue
        keep_records.append(record)
    return keep_records, filtered_count


def collect_candidates(
    *,
    sample_id: str,
    sequence_id: str,
    interval_idx: int,
    history_back: int,
    query_t_s: float,
    records: list[BoundingBoxRecord],
    bottom_ref_y: float,
    config: BBoxLoomingConfigV1,
) -> list[CandidateRow]:
    if len(records) < config.min_fit_points:
        return []

    times = np.asarray([record.timestamp_s for record in records], dtype=np.float64)
    weights = np.ones_like(times, dtype=np.float64)
    rows: list[CandidateRow] = []
    dimensions = dims_for_records(
        records,
        bottom_ref_y=bottom_ref_y,
        include_bottom_cue=config.include_bottom_cue,
    )
    for cue_name, values in dimensions.items():
        fit = _weighted_linear_fit(times, values, weights)
        if fit is None:
            continue
        slope_px_per_s, intercept_px = fit
        ref_px = float(slope_px_per_s * query_t_s + intercept_px)
        if ref_px <= config.min_width_px or slope_px_per_s <= config.min_slope_px_per_s:
            continue
        ttc_s = float(ref_px / slope_px_per_s)
        if not math.isfinite(ttc_s) or ttc_s < config.min_ttc_s or ttc_s > config.max_ttc_s:
            continue
        residual = _weighted_fit_residual(times, values, weights, slope_px_per_s, intercept_px)
        normalized_residual = float((residual or 0.0) / max(abs(ref_px), 1e-6))
        relative_slope = float(slope_px_per_s / max(abs(ref_px), 1e-6))
        rows.append(
            CandidateRow(
                sample_id=sample_id,
                sequence_id=sequence_id,
                interval_idx=interval_idx,
                cue_name=cue_name,
                history_back=history_back,
                fit_points=len(records),
                ttc_s=ttc_s,
                slope_px_per_s=float(slope_px_per_s),
                ref_px=ref_px,
                normalized_residual=normalized_residual,
                relative_slope=relative_slope,
            )
        )
    return rows


def collect_multiwindow_candidates(
    *,
    adapter: NativeSampleAdapter,
    sample_id: str,
    config: BBoxLoomingConfigV1,
) -> tuple[list[CandidateRow], str, int]:
    sample = adapter.reader.get_interval_sample(sample_id=sample_id)
    max_history_back = max(int(config.history_back_labels), int(config.history_min_back_labels))
    lo = sample.start_label_id - max_history_back
    hi = sample.start_label_id
    records = sorted(
        [record for record in adapter.bbox_records if lo <= record.label_id <= hi],
        key=lambda item: item.timestamp_s,
    )
    if len(records) < config.min_fit_points:
        return [], "BBOX_HISTORY_TOO_SHORT", len(records)

    if config.current_bbox_collapse_guard_enabled:
        current_records = [record for record in records if record.label_id == sample.start_label_id]
        current_record = current_records[-1] if current_records else None
        guard_lo = sample.start_label_id - max(1, int(config.current_bbox_collapse_history_back))
        previous_areas = [
            bbox_area(record)
            for record in records
            if guard_lo <= record.label_id < sample.start_label_id
        ]
        if current_record is not None and len(previous_areas) >= int(config.current_bbox_collapse_min_history):
            median_previous_area = float(np.median(np.asarray(previous_areas, dtype=np.float64)))
            if (
                median_previous_area > 0.0
                and bbox_area(current_record) / median_previous_area < float(config.current_bbox_collapse_area_ratio_min)
            ):
                records = [record for record in records if record.label_id != sample.start_label_id]
                if len(records) < config.min_fit_points:
                    return [], "BBOX_CURRENT_COLLAPSE_GUARD_NO_HISTORY", len(records)

    bottom_ref_y = bottom_reference_y(adapter, config)
    min_history_back = max(1, int(config.history_min_back_labels))

    def collect_from(input_records: list[BoundingBoxRecord]) -> list[CandidateRow]:
        rows: list[CandidateRow] = []
        for history_back in range(min_history_back, max_history_back + 1):
            window_lo = sample.start_label_id - history_back
            window_records = [record for record in input_records if window_lo <= record.label_id <= hi]
            rows.extend(
                collect_candidates(
                    sample_id=sample.sample_id,
                    sequence_id=sample.sequence_id,
                    interval_idx=sample.interval_idx,
                    history_back=history_back,
                    query_t_s=sample.query_t_s,
                    records=window_records,
                    bottom_ref_y=bottom_ref_y,
                    config=config,
                )
            )
        return rows

    candidate_rows = collect_from(records)
    if not candidate_rows:
        return [], "BBOX_FIT_FAIL", len(records)

    ttc_values = np.asarray([row.ttc_s for row in candidate_rows], dtype=np.float64)
    max_fit_points = max(row.fit_points for row in candidate_rows)
    if (
        config.history_bbox_collapse_guard_enabled
        and config.history_bbox_collapse_guard_require_low_confidence
        and config.quality_gate_enabled
    ):
        median_ttc_s = float(np.median(ttc_values))
        iqr_ttc_s = float(np.percentile(ttc_values, 75) - np.percentile(ttc_values, 25))
        iqr_over_median = iqr_ttc_s / max(abs(median_ttc_s), 1e-6)
        low_confidence = (
            len(candidate_rows) < int(config.quality_min_candidate_count)
            or max_fit_points < int(config.quality_min_fit_points)
            or iqr_over_median > float(config.quality_max_iqr_over_median)
        )
        if low_confidence:
            filtered_records, filtered_count = filter_history_bbox_collapses(records, config)
            if filtered_count > 0:
                filtered_candidate_rows = collect_from(filtered_records)
                if filtered_candidate_rows:
                    candidate_rows = filtered_candidate_rows
                    max_fit_points = max(row.fit_points for row in candidate_rows)
                elif len(filtered_records) < config.min_fit_points:
                    return [], "BBOX_HISTORY_COLLAPSE_GUARD_NO_HISTORY", len(filtered_records)

    return candidate_rows, "OK", max_fit_points


def group_for_row(row: dict[str, object]) -> str:
    failure_type = str(row.get("primary_failure_type") or "")
    if failure_type.startswith("APPARENT_HIGH_CONF_GEOMETRY_OVER"):
        return "APPARENT_HIGH_CONF_GEOMETRY_OVER"
    if failure_type.startswith("APPARENT_HIGH_CONF_GEOMETRY_UNDER"):
        return "APPARENT_HIGH_CONF_GEOMETRY_UNDER"
    if row.get("is_high_error") == "1":
        return "OTHER_HIGH_ERROR"
    return "LOW_ERROR_OR_MODERATE"


def error_pct(pred_s: float | None, gt_s: float | None) -> float | None:
    if pred_s is None or gt_s is None or gt_s <= 0.0:
        return None
    return abs(pred_s - gt_s) / gt_s * 100.0


def quantile_value(values: np.ndarray, q: float) -> float:
    return float(np.quantile(values, q))


def add_rule_predictions(row: dict[str, object]) -> None:
    interval_fraction = as_float(row.get("interval_fraction")) or 0.0
    area_ratio_med5 = as_float(row.get("area_ratio_med5"))
    q05 = as_float(row.get("candidate_q05_s"))
    q10 = as_float(row.get("candidate_q10_s"))
    q15 = as_float(row.get("candidate_q15_s"))
    q25 = as_float(row.get("candidate_q25_s"))
    q35 = as_float(row.get("candidate_q35_s"))
    q50 = as_float(row.get("candidate_q50_s"))
    q65 = as_float(row.get("candidate_q65_s"))
    q75 = as_float(row.get("candidate_q75_s"))
    gt = as_float(row.get("gt_ttc_s"))

    rules: dict[str, float | None] = {
        "rule_all_q10": q10,
        "rule_all_q25": q25,
        "rule_all_q50": q50,
        "rule_phase_early_q50_late_q10": q50 if interval_fraction <= 0.33 else q10 if interval_fraction >= 0.67 else q25,
        "rule_phase_early_q65_late_q10": q65 if interval_fraction <= 0.33 else q10 if interval_fraction >= 0.67 else q25,
        "rule_area_phase_q50_q10": (
            q50
            if interval_fraction <= 0.35 and area_ratio_med5 is not None and area_ratio_med5 >= 1.35
            else q10
            if interval_fraction >= 0.60 and area_ratio_med5 is not None and 0.80 <= area_ratio_med5 <= 1.30
            else q25
        ),
        "rule_area_phase_q65_q10": (
            q65
            if interval_fraction <= 0.35 and area_ratio_med5 is not None and area_ratio_med5 >= 1.35
            else q10
            if interval_fraction >= 0.60 and area_ratio_med5 is not None and 0.80 <= area_ratio_med5 <= 1.30
            else q25
        ),
    }
    for name, pred in rules.items():
        row[f"{name}_pred_s"] = fmt(pred)
        row[f"{name}_e_ttc_pct"] = fmt(error_pct(pred, gt))
    _ = (q05, q15, q35, q75)


def make_interval_row(
    *,
    metric_row: dict[str, str],
    type_row: dict[str, str],
    adapter: NativeSampleAdapter,
    candidates: list[CandidateRow],
    max_fit_points: int,
    config: BBoxLoomingConfigV1,
) -> dict[str, object]:
    sample = adapter.reader.get_interval_sample(sample_id=metric_row["sample_id"])
    gt_ttc_s = as_float(metric_row.get("gt_ttc_s"))
    pred_ttc_s = as_float(metric_row.get("ttc_est_s"))
    values = np.asarray([candidate.ttc_s for candidate in candidates], dtype=np.float64)
    cue_counts = Counter(candidate.cue_name for candidate in candidates)
    candidate_min = float(values.min())
    candidate_max = float(values.max())
    candidate_median = float(np.median(values))
    candidate_q25 = float(np.quantile(values, 0.25))
    candidate_q75 = float(np.quantile(values, 0.75))
    iqr_over_median = (candidate_q75 - candidate_q25) / max(abs(candidate_median), 1e-6)
    p90_p10_over_median = (
        float(np.quantile(values, 0.90)) - float(np.quantile(values, 0.10))
    ) / max(abs(candidate_median), 1e-6)
    quantile_preds = {q_key(q): quantile_value(values, q) for q in QUANTILES}
    quantile_errors = {key: error_pct(value, gt_ttc_s) for key, value in quantile_preds.items()}
    best_key = min(
        (key for key, value in quantile_errors.items() if value is not None),
        key=lambda key: float(quantile_errors[key] or 0.0),
        default="",
    )
    best_error = quantile_errors[best_key] if best_key else None
    features = bbox_ratio_features(
        adapter.bbox_records,
        start_label_id=sample.start_label_id,
        interval_idx=sample.interval_idx,
        interval_count=len(adapter.reader.interval_samples),
        history_back=config.history_back_labels,
    )
    row: dict[str, object] = {
        "sample_id": metric_row["sample_id"],
        "sequence_id": metric_row["sequence_id"],
        "interval_idx": metric_row["interval_idx"],
        "status": metric_row["status"],
        "primary_failure_type": type_row.get("primary_failure_type", ""),
        "diagnostic_group": group_for_row(type_row),
        "gt_ttc_s": fmt(gt_ttc_s),
        "v11_pred_ttc_s": fmt(pred_ttc_s),
        "v11_e_ttc_pct": fmt(as_float(metric_row.get("e_ttc_pct"))),
        "v11_pred_over_gt": fmt((pred_ttc_s / gt_ttc_s) if pred_ttc_s is not None and gt_ttc_s else None),
        "is_high_error": type_row.get("is_high_error", "0"),
        "candidate_count": len(candidates),
        "candidate_max_fit_points": max_fit_points,
        "candidate_min_s": fmt(candidate_min),
        "candidate_max_s": fmt(candidate_max),
        "candidate_iqr_over_median": fmt(iqr_over_median),
        "candidate_p90_p10_over_median": fmt(p90_p10_over_median),
        "candidate_width_count": cue_counts["width"],
        "candidate_height_count": cue_counts["height"],
        "candidate_diag_count": cue_counts["diag"],
        "candidate_sqrt_area_count": cue_counts["sqrt_area"],
        "candidate_bottom_offset_count": cue_counts["bottom_offset"],
        "best_quantile_key": best_key,
        "best_quantile_e_ttc_pct": fmt(best_error),
        **{key: fmt(value) if isinstance(value, float) else value for key, value in features.items()},
    }
    for key, value in quantile_preds.items():
        row[f"candidate_{key}_s"] = fmt(value)
        row[f"candidate_{key}_e_ttc_pct"] = fmt(quantile_errors[key])
    add_rule_predictions(row)
    return row


def rule_summary_rows(
    rows: list[dict[str, object]],
    *,
    group_name: str,
    high_error_threshold: float,
) -> list[dict[str, object]]:
    rule_names = [
        "rule_all_q10",
        "rule_all_q25",
        "rule_all_q50",
        "rule_phase_early_q50_late_q10",
        "rule_phase_early_q65_late_q10",
        "rule_area_phase_q50_q10",
        "rule_area_phase_q65_q10",
    ]
    output: list[dict[str, object]] = []
    for name in rule_names:
        summary = summarize_errors(rows, f"{name}_e_ttc_pct", high_error_threshold)
        output.append({"group": group_name, "rule": name, **summary})
    return output


def quantile_summary_rows(
    rows: list[dict[str, object]],
    *,
    group_name: str,
    high_error_threshold: float,
) -> list[dict[str, object]]:
    output: list[dict[str, object]] = []
    for q in QUANTILES:
        key = q_key(q)
        summary = summarize_errors(rows, f"candidate_{key}_e_ttc_pct", high_error_threshold)
        output.append({"group": group_name, "quantile": key, **summary})
    best_counts = Counter(str(row.get("best_quantile_key") or "") for row in rows)
    for row in output:
        row["oracle_best_count"] = best_counts.get(str(row["quantile"]), 0)
    return output


def feature_summary_rows(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    feature_keys = [
        "gt_ttc_s",
        "v11_pred_over_gt",
        "interval_fraction",
        "area_ratio_prev",
        "area_ratio_med5",
        "next_area_ratio_current",
        "candidate_count",
        "candidate_iqr_over_median",
        "candidate_p90_p10_over_median",
        "candidate_q25_s",
        "candidate_q50_s",
        "candidate_q75_s",
    ]
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[str(row["diagnostic_group"])].append(row)

    output: list[dict[str, object]] = []
    for group, group_rows in grouped.items():
        for key in feature_keys:
            values = [as_float(row.get(key)) for row in group_rows]
            numeric = [float(value) for value in values if value is not None]
            stats = safe_stats(numeric)
            output.append(
                {
                    "group": group,
                    "feature": key,
                    "count": stats["count"],
                    "mean": fmt(stats["mean"], digits=3),
                    "median": fmt(stats["median"], digits=3),
                    "p90": fmt(stats["p90"], digits=3),
                    "max": fmt(stats["max"], digits=3),
                }
            )
    return output


def write_summary_md(
    path: Path,
    *,
    run_dir: Path,
    interval_rows: list[dict[str, object]],
    quantile_rows: list[dict[str, object]],
    rule_rows: list[dict[str, object]],
    args: argparse.Namespace,
) -> None:
    group_counts = Counter(str(row["diagnostic_group"]) for row in interval_rows)
    all_quantile = [row for row in quantile_rows if row["group"] == "ALL_HIGH_CONF"]
    all_rules = [row for row in rule_rows if row["group"] == "ALL_HIGH_CONF"]
    over_quantile = [row for row in quantile_rows if row["group"] == "APPARENT_HIGH_CONF_GEOMETRY_OVER"]
    under_quantile = [row for row in quantile_rows if row["group"] == "APPARENT_HIGH_CONF_GEOMETRY_UNDER"]

    def table_quantiles(title: str, rows: list[dict[str, object]]) -> list[str]:
        lines = [
            f"## {title}",
            "",
            "| quantile | count | mean | p90 | over50 | oracle_best |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        for row in rows:
            lines.append(
                f"| `{row['quantile']}` | {row['count']} | {row['mean_e_ttc_pct']} | "
                f"{row['p90_e_ttc_pct']} | {row['over50_count']} | {row['oracle_best_count']} |"
            )
        lines.append("")
        return lines

    lines = [
        "# BBox High-Confidence Geometry Report",
        "",
        f"- run_dir: `{run_dir}`",
        f"- metrics_csv: `{args.metrics_csv.resolve()}`",
        f"- failure_types_csv: `{args.failure_types_csv.resolve()}`",
        f"- interval_count: `{len(interval_rows)}`",
        f"- group_counts: `{dict(group_counts)}`",
        "",
    ]
    lines.extend(table_quantiles("All High-Confidence Quantiles", all_quantile))
    lines.extend(table_quantiles("Apparent Geometry Over Quantiles", over_quantile))
    lines.extend(table_quantiles("Apparent Geometry Under Quantiles", under_quantile))
    lines.extend(
        [
            "## Rule Probes",
            "",
            "| rule | count | mean | p90 | over50 |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for row in all_rules:
        lines.append(
            f"| `{row['rule']}` | {row['count']} | {row['mean_e_ttc_pct']} | "
            f"{row['p90_e_ttc_pct']} | {row['over50_count']} |"
        )
    lines.extend(
        [
            "",
            "## Files",
            "",
            "- `IntervalCandidateQuantiles.csv`",
            "- `QuantileErrorSummary.csv`",
            "- `RuleProbeSummary.csv`",
            "- `FeatureGroupSummary.csv`",
            "- `WorstHighConfIntervals.csv`",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    metric_rows = read_csv(args.metrics_csv.resolve())
    type_rows = (
        read_csv(args.failure_types_csv.resolve())
        if args.failure_types_csv is not None and args.failure_types_csv.exists()
        else []
    )
    type_by_sample = {row["sample_id"]: row for row in type_rows}
    high_conf_metric_rows = [
        row
        for row in metric_rows
        if row.get("status") == "OK_BBOX_MULTI_Q25" and as_float(row.get("e_ttc_pct")) is not None
    ]

    config = BBoxLoomingConfigV1(
        history_back_labels=args.history_back,
        history_min_back_labels=args.history_min_back,
        max_ttc_s=args.max_ttc,
        fallback_to_lts_v1=False,
        cue_mode="multi_quantile",
        candidate_quantile=args.candidate_quantile,
        include_bottom_cue=True,
        quality_gate_enabled=True,
        quality_min_candidate_count=30,
        quality_min_fit_points=6,
        quality_max_iqr_over_median=0.7,
        quality_low_confidence_strategy="adaptive_quantile_v2",
        quality_reject_low_confidence_after_adaptive=True,
        current_bbox_collapse_guard_enabled=True,
        history_bbox_collapse_guard_enabled=True,
        history_bbox_collapse_guard_require_low_confidence=True,
    )
    run_ts = datetime.now().strftime("BBoxHighConfGeometryReport_%Y%m%d_%H%M%S")
    run_dir = args.output_root.resolve() / run_ts
    run_dir.mkdir(parents=True, exist_ok=True)

    adapters: dict[str, NativeSampleAdapter] = {}
    interval_rows: list[dict[str, object]] = []
    candidate_output_rows: list[dict[str, object]] = []
    try:
        for metric_row in high_conf_metric_rows:
            sequence_id = metric_row["sequence_id"]
            if sequence_id not in adapters:
                adapters[sequence_id] = NativeSampleAdapter(
                    sequence_id,
                    formal_root=args.formal_root.resolve(),
                )
            adapter = adapters[sequence_id]
            candidates, status, max_fit_points = collect_multiwindow_candidates(
                adapter=adapter,
                sample_id=metric_row["sample_id"],
                config=config,
            )
            if not candidates:
                continue
            row = make_interval_row(
                metric_row=metric_row,
                type_row=type_by_sample.get(metric_row["sample_id"], {}),
                adapter=adapter,
                candidates=candidates,
                max_fit_points=max_fit_points,
                config=config,
            )
            row["candidate_collect_status"] = status
            interval_rows.append(row)
            if row["diagnostic_group"] in {
                "APPARENT_HIGH_CONF_GEOMETRY_OVER",
                "APPARENT_HIGH_CONF_GEOMETRY_UNDER",
            }:
                for candidate in candidates:
                    candidate_dict = asdict(candidate)
                    for key in ("ttc_s", "slope_px_per_s", "ref_px", "normalized_residual", "relative_slope"):
                        candidate_dict[key] = fmt(float(candidate_dict[key]))
                    candidate_output_rows.append(candidate_dict)
    finally:
        for adapter in adapters.values():
            adapter.close()

    groups: dict[str, Callable[[dict[str, object]], bool]] = {
        "ALL_HIGH_CONF": lambda row: True,
        "APPARENT_HIGH_CONF_GEOMETRY_OVER": lambda row: row["diagnostic_group"] == "APPARENT_HIGH_CONF_GEOMETRY_OVER",
        "APPARENT_HIGH_CONF_GEOMETRY_UNDER": lambda row: row["diagnostic_group"] == "APPARENT_HIGH_CONF_GEOMETRY_UNDER",
        "LOW_ERROR_OR_MODERATE": lambda row: row["diagnostic_group"] == "LOW_ERROR_OR_MODERATE",
    }
    quantile_rows: list[dict[str, object]] = []
    rule_rows: list[dict[str, object]] = []
    for group_name, predicate in groups.items():
        group_rows = [row for row in interval_rows if predicate(row)]
        quantile_rows.extend(
            quantile_summary_rows(
                group_rows,
                group_name=group_name,
                high_error_threshold=args.high_error_threshold,
            )
        )
        rule_rows.extend(
            rule_summary_rows(
                group_rows,
                group_name=group_name,
                high_error_threshold=args.high_error_threshold,
            )
        )

    quantile_fieldnames = [
        "sample_id",
        "sequence_id",
        "interval_idx",
        "status",
        "primary_failure_type",
        "diagnostic_group",
        "gt_ttc_s",
        "v11_pred_ttc_s",
        "v11_e_ttc_pct",
        "v11_pred_over_gt",
        "is_high_error",
        "interval_fraction",
        "current_area",
        "area_ratio_prev",
        "area_ratio_med5",
        "next_area_ratio_current",
        "history_record_count",
        "history_collapse_count",
        "history_collapse_label_ids",
        "candidate_count",
        "candidate_max_fit_points",
        "candidate_min_s",
        "candidate_q05_s",
        "candidate_q10_s",
        "candidate_q15_s",
        "candidate_q25_s",
        "candidate_q35_s",
        "candidate_q50_s",
        "candidate_q65_s",
        "candidate_q75_s",
        "candidate_q90_s",
        "candidate_max_s",
        "candidate_iqr_over_median",
        "candidate_p90_p10_over_median",
        "candidate_q05_e_ttc_pct",
        "candidate_q10_e_ttc_pct",
        "candidate_q15_e_ttc_pct",
        "candidate_q25_e_ttc_pct",
        "candidate_q35_e_ttc_pct",
        "candidate_q50_e_ttc_pct",
        "candidate_q65_e_ttc_pct",
        "candidate_q75_e_ttc_pct",
        "candidate_q90_e_ttc_pct",
        "candidate_width_count",
        "candidate_height_count",
        "candidate_diag_count",
        "candidate_sqrt_area_count",
        "candidate_bottom_offset_count",
        "best_quantile_key",
        "best_quantile_e_ttc_pct",
        "rule_all_q10_pred_s",
        "rule_all_q10_e_ttc_pct",
        "rule_all_q25_pred_s",
        "rule_all_q25_e_ttc_pct",
        "rule_all_q50_pred_s",
        "rule_all_q50_e_ttc_pct",
        "rule_phase_early_q50_late_q10_pred_s",
        "rule_phase_early_q50_late_q10_e_ttc_pct",
        "rule_phase_early_q65_late_q10_pred_s",
        "rule_phase_early_q65_late_q10_e_ttc_pct",
        "rule_area_phase_q50_q10_pred_s",
        "rule_area_phase_q50_q10_e_ttc_pct",
        "rule_area_phase_q65_q10_pred_s",
        "rule_area_phase_q65_q10_e_ttc_pct",
        "candidate_collect_status",
    ]
    write_csv(run_dir / "IntervalCandidateQuantiles.csv", interval_rows, quantile_fieldnames)
    worst_rows = sorted(
        interval_rows,
        key=lambda item: float(item["v11_e_ttc_pct"] or 0.0),
        reverse=True,
    )[:120]
    write_csv(run_dir / "WorstHighConfIntervals.csv", worst_rows, quantile_fieldnames)
    write_csv(
        run_dir / "HighConfGeometryCandidates.csv",
        candidate_output_rows,
        [
            "sample_id",
            "sequence_id",
            "interval_idx",
            "cue_name",
            "history_back",
            "fit_points",
            "ttc_s",
            "slope_px_per_s",
            "ref_px",
            "normalized_residual",
            "relative_slope",
        ],
    )
    write_csv(
        run_dir / "QuantileErrorSummary.csv",
        quantile_rows,
        [
            "group",
            "quantile",
            "count",
            "mean_e_ttc_pct",
            "median_e_ttc_pct",
            "p90_e_ttc_pct",
            "max_e_ttc_pct",
            "over50_count",
            "oracle_best_count",
        ],
    )
    write_csv(
        run_dir / "RuleProbeSummary.csv",
        rule_rows,
        [
            "group",
            "rule",
            "count",
            "mean_e_ttc_pct",
            "median_e_ttc_pct",
            "p90_e_ttc_pct",
            "max_e_ttc_pct",
            "over50_count",
        ],
    )
    write_csv(
        run_dir / "FeatureGroupSummary.csv",
        feature_summary_rows(interval_rows),
        ["group", "feature", "count", "mean", "median", "p90", "max"],
    )

    payload = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "metrics_csv": str(args.metrics_csv.resolve()),
        "failure_types_csv": str(args.failure_types_csv.resolve()),
        "formal_root": str(args.formal_root.resolve()),
        "config": asdict(config),
        "high_conf_metric_count": len(high_conf_metric_rows),
        "interval_count": len(interval_rows),
        "group_counts": dict(Counter(str(row["diagnostic_group"]) for row in interval_rows)),
    }
    (run_dir / "Config.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_summary_md(
        run_dir / "Summary.md",
        run_dir=run_dir,
        interval_rows=interval_rows,
        quantile_rows=quantile_rows,
        rule_rows=rule_rows,
        args=args,
    )

    print(f"[Done] run_dir: {run_dir}")
    print(f"[Done] summary: {run_dir / 'Summary.md'}")


if __name__ == "__main__":
    main()
